#ifndef RESOURCE_H
#define RESOURCE_H

#define IDI_MAIN 101

#define IDD_SPLASH 101

#define IDC_SPLASH_BUSY 101
#define IDC_SPLASH_RECENT 102
#define IDC_SPLASH_NEW 103
#define IDC_SPLASH_RECENT_CONTAINER 104

#endif
